{{- $chartName := include "discrete-cleanup.name" . -}}
{{- $tracingUrl := include "discrete-cleanup.tracingUrl" . -}}
{{- $metricsUrl := include "discrete-cleanup.metricsUrl" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}
  LOG_PRETTY_PRINT_ENABLED: {{ .Values.env.logPrettyPrintEnabled | quote }}
  {{ if .Values.env.tracing.enabled }}
  TELEMETRY_TRACING_ENABLED: 'true'
  TELEMETRY_TRACING_URL: {{ $tracingUrl }}
  {{ end }}
  {{ if .Values.env.metrics.enabled }}
  TELEMETRY_METRICS_ENABLED: 'true'
  TELEMETRY_METRICS_URL: {{ $metricsUrl }}
  {{ end }}
  JOB_MANAGER_URL: {{ .Values.rasterCommon.serviceUrls.jobManager | quote }}
  MAPPROXY_API_URL: {{ .Values.rasterCommon.serviceUrls.mapproxyApi | quote }}
  TILES_STORAGE_PROVIDER: {{ .Values.rasterCommon.storage.tilesStorageProvider | quote }}
  S3_API_VERSION: {{ .Values.env.s3.apiVersion | quote }}
  S3_ENDPOINT: {{ .Values.rasterCommon.storage.s3.endpointUrl | quote }}
  S3_SSL_ENABLED: {{ .Values.rasterCommon.storage.s3.sslEnabled | quote }}
  S3_MAX_RETRIES: {{ .Values.env.s3.maxRetries | quote }}
  S3_BUCKET: {{ .Values.rasterCommon.storage.s3.tilesBucket | quote }}
  BATCH_SIZE_DISCRETE_LAYERS: {{ .Values.env.batchSize.discreteLayers | quote }}
  BATCH_SIZE_DIRECTORY_TIFF_DELETION: {{ .Values.env.batchSize.tiffDirectoryDeletion | quote }}
  BATCH_SIZE_TILES_DELETION: {{ .Values.env.batchSize.tilesDeletion | quote }}
  FAILED_INGESTION_CLEANUP_DELAY_DAYS: {{ .Values.env.failedCleanupDelayDays.ingestion | quote }}
  FAILED_SYNC_CLEANUP_DELAY_DAYS: {{ .Values.env.failedCleanupDelayDays.sync | quote }}
  HTTP_RETRY_ATTEMPTS: {{ .Values.env.httpRetry.attempts | quote }}
  HTTP_RETRY_DELAY: {{ .Values.env.httpRetry.delay | quote }}
  HTTP_RETRY_RESET_TIMEOUT: {{ .Values.env.httpRetry.shouldResetTimeout | quote }}
  NEW_INGESTION_JOB_TYPE: {{ .Values.rasterCommon.jobManagement.ingestion.new.jobType | quote }}
  UPDATE_INGESTION_JOB_TYPE: {{ .Values.rasterCommon.jobManagement.ingestion.update.jobType | quote }}
  SWAP_UPDATE_INGESTION_JOB_TYPE: {{ .Values.rasterCommon.jobManagement.ingestion.updateSwap.jobType | quote }}
  INCOMING_SYNC_JOB_TYPE: {{ .Values.rasterCommon.jobManagement.sync.incoming.JobType | quote }}
  EXPORT_JOB_TYPE: {{ .Values.rasterCommon.jobManagement.exporter.JobType | quote }}
  CLEANUP_TYPES_FAILED_INGESTION_TASKS: {{ .Values.env.cleanupTypes.failedIngestionTasks | quote }}
  CLEANUP_TYPES_SUCCESSFUL_INGESTION: {{ .Values.env.cleanupTypes.successfulIngestion | quote }}
  CLEANUP_TYPES_FAILED_INCOMING_SYNC_TASKS: {{ .Values.env.cleanupTypes.failedIncomingSyncTasks | quote }}
  CLEANUP_TYPES_SUCCESSFUL_SWAP_UPDATE_TASKS: {{ .Values.env.cleanupTypes.successfulSwapUpdate | quote }}
  FS_BLACK_LIST_SOURCES_LOCATION: {{ .Values.env.fs.blacklist_sources_location | toJson | quote }}
{{- end }}
