{{- $releaseName := .Release.Name -}}
{{- $chartName := include "discrete-cleanup.name" . -}}
{{- $cloudProviderFlavor := include "discrete-cleanup.cloudProviderFlavor" . -}}
{{- $cloudProviderDockerRegistryUrl := include "discrete-cleanup.cloudProviderDockerRegistryUrl" . -}}
{{- $imageTag := include "discrete-cleanup.tag" . -}}
{{- $cloudProviderImagePullSecretName := include "discrete-cleanup.cloudProviderImagePullSecretName" . -}}

{{- if .Values.enabled -}}

{{ $sslSecretName := ternary .Values.authentication.ssl.externalSecretName (printf "%s%s" .Release.Name "-open-ssl") .Values.authentication.ssl.useExternal }}

{{- if .Values.authentication.ssl.enabled }}
{{- if and .Values.authentication.ssl.useExternal (not .Values.authentication.ssl.externalSecretName) }}
{{- fail "When using external ssl secret the value for .Values.authentication.ssl.externalSecretName should be set" }}
{{- end }}
{{- end }}

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ $releaseName }}-{{ $chartName }}
  labels:
    app: {{ $chartName }}
    component: {{ $chartName }}
    environment: {{ include "discrete-cleanup.environment" . }}
    release: {{ $releaseName }}
    {{- include "discrete-cleanup.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.cron.schedule | quote }}
  successfulJobsHistoryLimit: {{ .Values.cron.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cron.failedJobsHistoryLimit }}
  concurrencyPolicy: {{ .Values.cron.concurrencyPolicy }}
  jobTemplate:
    spec:
      template:
        spec:
          {{- if $cloudProviderImagePullSecretName }}
          imagePullSecrets:
            - name: {{ $cloudProviderImagePullSecretName | quote }}
          {{- end }}
          restartPolicy: {{ .Values.cron.restartPolicy }}
          containers:
            - name: {{ $releaseName }}-{{ $chartName }}-deployment
              {{- with .Values.image }}
              image: {{ $cloudProviderDockerRegistryUrl }}{{ .repository }}:{{ $imageTag }}
              {{- end }}
              env:
              {{- if eq (upper .Values.rasterCommon.storage.tilesStorageProvider) "S3" }}
                - name: S3_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.rasterCommon.storage.s3.secretName }}
                      key: accessKeyId
                - name: S3_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.rasterCommon.storage.s3.secretName }}
                      key: secretAccessKey
                {{- else }}
                - name: FS_TILES_LOCATION
                  value: /tiles
                {{- end }}
                - name: FS_SOURCES_LOCATION
                  value: /layerSources
                {{- if .Values.rasterCommon.ca.secretName }}
                - name: REQUESTS_CA_BUNDLE
                  value: {{ printf "%s/%s" .Values.rasterCommon.ca.path .Values.rasterCommon.ca.key | quote }}
                - name: NODE_EXTRA_CA_CERTS
                  value: {{ printf "[%s/%s]" .Values.rasterCommon.ca.path .Values.rasterCommon.ca.key | quote }}
                {{- end }}
              envFrom:
                - configMapRef:
                    name: {{ $releaseName }}-{{ $chartName }}-configmap
              volumeMounts:
               {{- if or .Values.env.cleanupTypes.failedIngestionTasks .Values.env.cleanupTypes.successfulIngestion }}
                - name: sources-volume
                  mountPath: /layerSources
                  {{- if .Values.rasterCommon.storage.fs.ingestionSourcePvc.subPath }}
                  subPath: {{ .Values.rasterCommon.storage.fs.ingestionSourcePvc.subPath }}
                  {{- end }}
                {{- end }}
                  {{- if ne (upper .Values.rasterCommon.storage.tilesStorageProvider) "S3" }}
                - name: tiles-folder
                  mountPath: /tiles
                  {{- if .Values.rasterCommon.storage.fs.internalPvc.tilesSubPath }}
                  subPath: {{ .Values.rasterCommon.storage.fs.internalPvc.tilesSubPath }}
                  {{- end }}
                {{- end }}
                {{- if .Values.rasterCommon.ca.secretName }}
                - mountPath: {{ printf "%s/%s" .Values.rasterCommon.ca.path .Values.rasterCommon.ca.key | quote }}
                  name: root-ca
                  subPath: {{ quote .Values.rasterCommon.ca.key }}
                {{- end }}
                {{- if .Values.authentication.ssl.enabled }}
                - name: open-ssl
                  mountPath: "/etc/ssl/etc/ssl/openssl.cnf"
                  subPath: "openssl.cnf"
                {{- end }}
            {{- if .Values.resources.enabled }}
              resources:
                {{- toYaml .Values.resources.value | nindent 16 }}
              {{- end }}
          volumes:
          {{- if or .Values.env.cleanupTypes.failedIngestionTasks .Values.env.cleanupTypes.successfulIngestion }}
            - name: sources-volume
            {{- if .Values.local.fs.sources.useEmptyDir }}
              emptyDir: {}
            {{- else }}
              persistentVolumeClaim:
                claimName: {{ .Values.rasterCommon.storage.fs.ingestionSourcePvc.name }}
            {{- end }}
          {{- end }}
            {{- if ne (upper .Values.rasterCommon.storage.tilesStorageProvider) "S3" }}
            - name: tiles-folder
              {{- if .Values.local.fs.tiles.useEmptyDir }}
              emptyDir: {}
              {{- else }}
              persistentVolumeClaim:
                claimName: {{ .Values.rasterCommon.storage.fs.internalPvc.name }}
              {{- end }}
            {{- end }}
            {{- if .Values.rasterCommon.ca.secretName }}
            - name: root-ca
              secret:
                secretName: {{ .Values.rasterCommon.ca.secretName }}
            {{- end }}
            {{- if .Values.authentication.ssl.enabled }}
            - name: open-ssl
              secret:
                secretName: {{ $sslSecretName }}
            {{- end }}
{{- end -}}
