{{- $releaseName := .Release.Name -}}
{{- $chartName := include "ts-script-boilerplate.name" . -}}
{{- $cloudProviderFlavor := include "ts-script-boilerplate.cloudProviderFlavor" . -}}
{{- $cloudProviderDockerRegistryUrl := include "ts-script-boilerplate.cloudProviderDockerRegistryUrl" . -}}
{{- $imageTag := include "ts-server-boilerplate.tag" . -}}
{{- if .Values.enabled -}}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ $releaseName }}-{{ $chartName }}
  labels:
    app: {{ $chartName }}
    component: {{ $chartName }}
    environment: {{ include "ts-script-boilerplate.environment" . }}
    release: {{ $releaseName }}
    {{- include "ts-script-boilerplate.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.cron.schedule | quote }}
  successfulJobsHistoryLimit: {{ .Values.cron.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cron.failedJobsHistoryLimit }}
  concurrencyPolicy: {{ .Values.cron.concurrencyPolicy }}
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: {{ .Values.cron.restartPolicy }}
          containers:
            - name: {{ $releaseName }}-{{ $chartName }}-deployment
              {{- with .Values.image }}
              image: {{ $cloudProviderDockerRegistryUrl }}{{ .repository }}:{{ $imageTag }}
              {{- end }}
              env:
                - name: S3_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.s3Secret.name }}
                      key: accessKeyId
                - name: S3_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.s3Secret.name }}
                      key: secretAccessKey
                - name: FS_TILES_LOCATION
                  value: {{ .Values.storage.tilesPersistenceDisk.mountPath }}
                - name: FS_SOURCES_LOCATION
                  value: {{ .Values.storage.tiffsPersistenceDisk.mountPath }}
              envFrom:
                - configMapRef:
                    name: {{ $releaseName }}-{{ $chartName }}-configmap
              volumeMounts:
                - name: sources-volume
                  mountPath: {{ .Values.discreteCleanup.tiffsPersistenceDisk.mountPath }}
                  {{- if .Values.storage.tiffsPersistenceDisk.sourcesSubPath }}
                  subPath: {{ .Values.storage.tiffsPersistenceDisk.sourcesSubPath }}
                  {{- end }}
                - name: tiles-folder
                  mountPath: {{ .Values.discreteCleanup.tilesPersistenceDisk.mountPath }}
                  {{- if .Values.storage.tilesPersistenceDisk.sourcesSubPath }}
                  subPath: {{ .Values.storage.tilesPersistenceDisk.sourcesSubPath }}
                  {{- end }}
              volumes:
                - name: sources-volume
                {{- if .Values.storage.tiffsPersistenceDisk.useEmptyDir }}
                  emptyDir: {}
                {{- else }}
                  persistentVolumeClaim:
                    claimName: {{ .Values.storage.tiffsPersistenceDisk.pvcName }}
                {{- end }}
                - name: tiles-folder
                {{- if .Values.storage.tilesPersistenceDisk.useEmptyDir }}
                  emptyDir: {}
                {{- else }}
                  persistentVolumeClaim:
                    claimName: {{ .Values.storage.tilesPersistenceDisk.pvcName }}
                {{- end }}
              {{- if .Values.resources.enabled }}
              resources:
                {{- toYaml .Values.resources.value | nindent 16 }}
              {{- end }}
{{- end -}}
