{{- if .Values.local.s3.secret.create -}}
{{- $s3 := (include "common.s3.merged" .) | fromYaml }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $s3.secretName }}
type: Opaque
stringData:
  accessKeyId: {{ .Values.local.s3.secret.accessKeyId | quote }}
  secretAccessKey: {{ .Values.local.s3.secret.secretAccessKey | quote }}
{{- end }}
