{{- if .Values.local.s3.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.rasterCommon.storage.s3.secretName }}
type: Opaque
stringData:
  accessKeyId: {{ .Values.local.s3.secret.accessKeyId | quote }}
  secretAccessKey: {{ .Values.local.s3.secret.secretAccessKey | quote }}
{{- end }}
